name: automation-test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  django-test:
    runs-on: ubuntu-latest
    env:
      APP_NAME: next-type
      USER_NAME: next-type
      EXEC_ENV: develop
      DJANGO_SETTINGS_MODULE: next_type.settings
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      FRONTEND_DEBUG_PORT: 3000
      BACKEND_DEBUG_PORT: 8000
      URL_SCHEME: http
      HOST: localhost
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: set-userid
        run: |
          echo "USER_ID=$(id -u)" >> $GITHUB_ENV
      - name: compose-up
        shell: bash
        run: |
          docker compose -f docker-compose.yml -f docker-develop.yml up -d backend --wait
      - name: container-log
        if: failure()
        run: |
          docker inspect --format='{{json .State.Health}}' backend | jq .
          docker compose -f docker-compose.yml -f docker-develop.yml logs --tail=50 backend
      - name: run-test
        run: |
          docker compose exec -T backend python manage.py test
